### ISSUE TITLE
Issue RSS-ECOMM-1_02: Set up folder structure 📁

### ISSUE THREAD

**Issue by Tetiana-KET** [Maksim99745/eCommerce-Application#4]
Description 📝
Set up a clear and organized folder structure within the repository, ensuring a maintainable and scalable codebase. By organizing the codebase properly, it will be easier for team members to navigate and contribute code efficiently. 🧭

Acceptance Criteria 📚
There is a well-defined folder structure for different components, features, and assets. 📂
The folder structure allows for easy navigation and identification of the project's different parts. 📍

**Comment by Maksim99745** [comment]
Coverage per folder:
After this task, we have to prepare a quality matrix utilizing Jest.
